name: ${project.name}
description: ${project.description}
main: ${project.main}
version: ${project.version}
api-version: ${project.api.version}
authors:
  - gaia-03
  - IllyrionSoftware
load: ${project.load}
